services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: rpg
      POSTGRES_USER: rpg
      POSTGRES_PASSWORD: rpg
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
